example-app-1/routes/web.php
<?php

use App\Http\Controllers\GoogleController;
use App\Http\Controllers\UserController;
use App\Models\Role;
use App\Models\User;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['prefix' => '/auth'], function () {
    Route::get('/google', [GoogleController::class,'redirectToGoogle']);
    Route::get('/google/callback', [GoogleController::class,'handleGoogleCallback']);
});

Route::group( ['middleware' => 'admin', 'prefix' => 'admin'], function () {
    Route::resource('/users', UserController::class);
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

example-app-1/app/Models/Role.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
    ];

    public function users(): \Illuminate\Database\Eloquent\Relations\BelongsToMany
    {
        return $this->belongsToMany(User::class, 'roles_has_users');
    }
}

example-app-1/app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;

class User extends Authenticatable implements HasMedia
{
    use HasApiTokens, HasFactory, Notifiable, InteractsWithMedia;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'is_block',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function roles(): \Illuminate\Database\Eloquent\Relations\BelongsToMany
    {
        return $this->belongsToMany(Role::class, 'roles_has_users');
    }

    public function isAdmin(): bool
    {
        return $this->roles()->where('name', 'admin')->exists();
    }

    public function registerMediaCollections(): void
    {
        $this->addMediaCollection('avatar')->singleFile();
    }
}

example-app-1/app/Http/Controllers/Api/UserController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Resources\UserCollection;
use App\Models\User;
use Illuminate\Http\Request;
use function response;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\JsonResponse|\Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $users = User::select('name', 'email')->whereNotNull('google_id')->where('is_block', '=', 0)->get();
        return response()->json(['success' => true, 'users' => new UserCollection($users)]);
    }
}

example-app-1/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

example-app-1/app/Http/Controllers/GoogleController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;
use Laravel\Socialite\Facades\Socialite;

class GoogleController extends Controller
{
    public function redirectToGoogle()
    {
        return Socialite::driver('google')->redirect();
    }

    public function handleGoogleCallback()
    {
        try {
            $user = Socialite::driver('google')->user();
        } catch (\Exception $e) {
            return redirect('/login');
        }
        if(explode("@", $user->email)[1] !== 'gmail.com'){
            return redirect()->to('/');
        }
        $existingUser = User::where('email', $user->email)->first();
        if($existingUser){
            auth()->login($existingUser, true);
        } else {
            $newUser = new User;
            $newUser->name = $user->name;
            $newUser->email = $user->email;
            $newUser->google_id = $user->id;
            $newUser->save();
            auth()->login($newUser, true);
        }
        return redirect()->to('/home');
    }
}

example-app-1/app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

example-app-1/app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Resources\UserCollection;
use App\Models\User;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @param Request $request
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\JsonResponse|\Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::all();
        return view('users.index', compact('users'));
    }

    /**
     * Display the specified resource.
     *
     * @param User $user
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function show(User $user)
    {
        return view('users.show', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param User $user
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function edit(User $user)
    {
        return view('users.update', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param User $user
     * @return RedirectResponse
     */
    public function update(Request $request, User $user)
    {
        $user->update($request->all());
        if ($request->hasFile('avatar') && $request->file('avatar')->isValid()) {
            $user->addMediaFromRequest('avatar')->toMediaCollection('avatar');
        }
        return redirect()->route('users.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param User $user
     * @return RedirectResponse
     */
    public function destroy(Request $request, User $user)
    {
//        $numberOfAdmins = DB::table('roles_has_users')
//            ->select()
//            ->join('users', 'users.id', '=', 'roles_has_users.user_id')
//            ->join('roles', 'roles.id', '=', 'roles_has_users.role_id')
//            ->where('roles.name', 'admin')
//            ->get()
//            ->count();
//        dd($user);
        if (Auth::user()->id === $user->id) {
            \Session::flash('message', 'You cannot delete yourself !');
            return back();
        } else {
            $user->delete();
            return redirect()->route('users.index');
        }
    }
}

example-app-1/resources/views/home.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">{{ __('Dashboard') }}</div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif

                        {{ __('You are logged in!') }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

example-app-1/resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav me-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ms-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    @if(Auth::user()->getFirstMediaUrl('avatar', 'thumb'))
                                        <img src="{{Auth::user()->getFirstMediaUrl('avatar', 'thumb') }}" width="90px" height="90px">
                                        {{ Auth::user()->name }}
                                    @else
                                        {{ Auth::user()->name }}
                                    @endif
                                </a>

                                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                    @if(Auth::user()->isAdmin())
                                    <a class="dropdown-item" href="{{ route('users.index') }}">Admin</a>
                                    @endif
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

example-app-1/resources/views/users/index.blade.php
@extends('layouts.app')

@section('content')
    @if (Session::has('message'))
        <div class="alert alert-danger">{{ Session::get('message') }}</div>
    @endif
    <table class="table">
        <thead>
        <tr>
            <th>Photo</th>
            <th>Name</th>
            <th>Email</th>
            <th>Is_block</th>
            <th>Actions</th>
            <th>Roles</th>
        </tr>
        </thead>
        <tbody>
        @foreach($users as $user)
            <tr>
                @if($user->getFirstMediaUrl('avatar', 'thumb'))
                    <td><img src="{{$user->getFirstMediaUrl('avatar', 'thumb') }}" width="90px" height="90px"></td>
                @else
                    <td>No photo</td>
                @endif
                <td>{{$user->name}}</td>
                <td>{{$user->email}}</td>
                <td>{{$user->is_block ? 'Blocked' : 'Not blocked'}}</td>
                <td>
                    <form method="post" action="{{ route('users.destroy', $user) }}">
                        @csrf
                        <a type="button" class="btn btn-info" href="{{ route('users.show', $user) }}">Show</a>
                            <a type="button" class="btn btn-warning" href="{{ route('users.edit', $user) }}">Update</a>
                        @method('DELETE')
                            <input class="btn btn-danger" type="submit" value="Delete">
                    </form>
                </td>
                <td>
                    @foreach ($user->roles as $role)
                        @if($role->name)
                            <span class="badge bg-primary">{{ $role->name }}</span>
                        @endif
                    @endforeach
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
@endsection

example-app-1/resources/views/users/show.blade.php
@extends('layouts.app')

@section('content')
    <h1>User <b>{{ $user->name }}</b></h1>
    <div class="col-md-12">
        <table class="table">
            <tbody>
            <tr>
                <th>
                    Field
                </th>
                <th>
                    Value
                </th>
            </tr>
            <tr>
                <td>ID</td>
                <td>{{ $user->id }}</td>
            </tr>
            <tr>
                <td>Photo</td>
                @if($user->getFirstMediaUrl('avatar', 'thumb'))
                    <td><img src="{{$user->getFirstMediaUrl('avatar', 'thumb') }}" width="90px" height="90px"></td>
                @else
                    <td>No photo</td>
                @endif
            </tr>
            <tr>
                <td>Name</td>
                <td>{{ $user->name }}</td>
            </tr>
            <tr>
                <td>Email</td>
                <td>{{ $user->email }}</td>
            </tr>
            <tr>
                <td>Is_block</td>
                <td>{{ $user->is_block }}</td>
            </tr>
            <tr>
                <td>Google_id</td>
                <td>{{ $user->google_id }}</td>
            </tr>
            <tr>
                <td>Created_at</td>
                <td>{{ $user->created_at }}</td>
            </tr>
            <tr>
                <td>Updated_at</td>
                <td>{{ $user->updated_at }}</td>
            </tr>
            </tbody>
        </table>
        <div>
            <a type="button" class="btn btn-dark" href="{{ route('users.index') }}">Back</a>
        </div>
    </div>
@endsection

example-app-1/resources/views/users/update.blade.php
@extends('layouts.app')

@section('content')
   <div style="margin-left: 5px">
       <h1>Update user <b>{{ $user->name }}</b></h1>
       <form method="POST" action="{{ route('users.update', $user) }}" enctype="multipart/form-data">
           @method('PUT')
           @csrf
           <div >
               <input type="hidden" name="is_block" value="0" {{ $user->is_block ? "checked" : '' }}>
               <input type="checkbox" name="is_block" value="1" {{ $user->is_block ? "checked" : '' }}>
               <label>Block user</label>
           </div>

           <div class="row mt-3">
               <div class="col-sm-4">
                   <input name="name" type="text" class="form-control @error('name') alert alert-danger @enderror"
                          placeholder="Name" aria-label="Name" value="{{ $user->name }}">
                   @error('name')
                   <div class="form-text" style=" color: red">{{ $message }}</div>
                   @enderror
               </div>
           </div>

           <div class="row mt-3 ">
               <div class="col-sm-4">
                   <input name="email" type="text" class="form-control @error('email') alert alert-danger @enderror"
                          placeholder="Email" aria-label="Email" value="{{ $user->email }}">
                   @error('email')
                   <div class="form-text" style=" color: red">{{ $message }}</div>
                   @enderror
               </div>
           </div>

           <div class="row mt-3">
               <div class="col-sm-4">
                   <tr>
                       @if($user->getFirstMediaUrl('avatar', 'thumb'))
                           <td><img src="{{$user->getFirstMediaUrl('avatar', 'thumb') }}" width="90px" height="90px"></td>
                       @endif
                   </tr>
               </div>
               <div class="row mt-3">
                   <input type="file" name="avatar">
               </div>
           </div>

           <div class="row mt-3">
               <div class="col-sm-4">
                   <input class="btn btn-warning" type="submit" value="Save">
                   <a type="button" class="btn btn-dark" href="{{ route('users.index') }}">Cancel</a>
               </div>
           </div>
       </form>
   </div>
@endsection